
[colors]
draw_bold_text_with_bright_colors = true
#unfocused_hollow = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x1d202f"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x24283b"
foreground = "0xc0caf5"

[font]
size = 15.0
normal = { family = "UbuntuMono Nerd Font Mono", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

#[font.normal]
#family = "Ubuntu Mono Nerd Font Complete Mono"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "~Search"
mods = "Control"

[[keyboard.bindings]]
action = "First"
key = "Key0"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi|~Search"
mods = "Shift"

[window]
opacity = 1

[general]
live_config_reload = true
